spring:
  application:
    name: annexify-admin-bff

server:
  port: 8081
  servlet:
    context-path: /api/admin

annexify:
  service:
    central:
      url: http://localhost:8080
    storage:
      url: http://localhost:8083